site_name: T.J. Hob
site_author: T.J. Hob
site_description: The personal website of T.J. Hob - professional data dork, amateur homesteader, something of a hacker
site_url: https://tjhob.com
theme:
  name: terminal
  palette: dark
  custom_dir: overrides
  features:
    - navigation.side.indexes
nav:
  - Home: index.md
  - Past Projects: projects/past_projects.md
  - Long Form:
      - Back to the Land: long/back_to_the_land.md
  - Updates:
      - 2024-09: 2024/2024-09.md
      - 2024-10: 2024/2024-10.md
      - 2024-11: 2024/2024-11.md
  - Tech Mastodon: https://fedia.social/@TJHob
  - Farm Mastodon: https://homestead.social/@TJHob
plugins:
  - rss:
      abstract_chars_count: -1
